rebuy-de/aws-nuke

- .jenkins.yml
- .travis.yml
> add .travis.yml

- cmd/nuke.go
@rebuy-de/it-platform Please review.
> Add support for assuming roles via ~/.aws/config

- README.md
> add use cases

- README.md
> improve development status in README

- cmd/config.go
- cmd/log.go
@rebuy-de/prp-aws-nuke - Prettify warning for deprecated resource types.
> Pretty warning

- cmd/config.go
- resources/listers.go
- resources/rds-clusters.go
@rebuy-de/prp-aws-nuke - PTAL
* RDSCluster -> RDSDBCluster
> Rename rds resouce

- cmd/nuke.go
- cmd/params.go
- cmd/root.go
- pkg/awsutil/session.go
While doing #66 I stumbled over a lot things which I also would need to refactor. To keep the PRs clean I am splitting it where possible.
Also the `cmd` package is way too big. Therefore I am introducing the `pkg` structure, like we did in other projects. Eventually we will add other packages and also move the `resources` package there.
> create awsutil package

- resources/kms-keys.go
Figuring out by alias is error prone and unnecessary.
> skip managed KMS keys

- glide.lock
- glide.yaml
> aws sdk 1.13.8

- resources/ecr-repository.go
Prettify ECR repository resource to provide a better example for pagination.
> prettify ECR repository resource

- resources/cloudwatch-alarms.go
- resources/cloudwatch-dashboards.go
I know that the slice casting in the remove isnt ideal.  If you have a better way (and frankly the right way) to do it, let me know.
> Add Cloudwatch Dashboards and Alarms

- resources/apigateway-apikeys.go
- resources/apigateway-clientcertificates.go
- resources/apigateway-domainnames.go
- resources/apigateway-restapis.go
- resources/apigateway-usageplans.go
- resources/apigateway-vpclinks.go
> Add API Gateway cleanup

- resources/clouddirectory-directories.go
- resources/clouddirectory-schemas.go
> CloudDirectory Service Directory and Schema delete

- cmd/scan.go
- pkg/awsutil/errors.go
- pkg/awsutil/session.go
This might help #112 and #63 
Its not the most "elegant" solution but considering we can't even get a response from AWS which says ServiceUnsupported or the like, it might be all we can.  The only alternative I can think of is making a mapping of all services to all endpoints which will get messy to maintain.
> Proposed fix for some of the errors around new services

- README.md
- cmd/root.go
- pkg/awsutil/session.go
> add session token support

- glide.lock
- glide.yaml
Update AWS SDK. Might resolve #114.
> bump AWS SDK v1.13.17

- resources/waf-rules.go
- resources/waf-webacl-rule-attachements.go
- resources/waf-webacls.go
This is not full coverage of the product but does cover all "cost"-based assets
> Add WAF ACL's and Rules

- resources/mediaconvert-jobtemplates.go
- resources/mediaconvert-presets.go
- resources/mediaconvert-queues.go
Note, this uses a custom endpoint per customer per region.  I would be careful how this tests in the CI going forward.
> Add MediaConvert coverage

- pkg/awsutil/session.go
> See https://github.com/aws/aws-sdk-go/issues/1853. Fixes #65.
> fix S3 with empty directories

- README.md
- cmd/nuke.go
- config/example.yaml
- glide.lock
- glide.yaml
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/config/filter.go
- pkg/config/filter_test.go
> Fixes #150
I think this is the worst code I ever have written, but I do not see any better way with this complicated YAML library.
@rebuy-de/prp-aws-nuke Please tell me what you think before I continue.
> Improve filters

- resources/cloudfront-distributiondeployments.go
- resources/cloudfront-distributions.go
global - CloudFrontDistribution - 'E3S4CW6FECBL7Y' - DistributionNotDisabled: The distribution you are trying to delete has not been disabled.
status code: 409, request id: fe2b0707-2d26-11e8-a990-3d15bd6d3e24
global - CloudFrontDistributionDeployment - 'E3S4CW6FECBL7Y' - waiting
Removal requested: 1 waiting, 1 failed, 0 skipped, 0 finished
global - CloudFrontDistribution - 'E3S4CW6FECBL7Y' - DistributionNotDisabled: The distribution you are trying to delete has not been disabled.
status code: 409, request id: 01431d13-2d27-11e8-a990-3d15bd6d3e24
global - CloudFrontDistributionDeployment - 'E3S4CW6FECBL7Y' - waiting
Removal requested: 1 waiting, 1 failed, 0 skipped, 0 finished
global - CloudFrontDistribution - 'E3S4CW6FECBL7Y' - removed
global - CloudFrontDistributionDeployment - …
> Remove CloudFront Distributions

- pkg/awsutil/session.go
> fixes #157
@tomvachon Would that solve the problem? Could you verify it?
> add fallback for missing services in endpoint list

- resources/mediastore-containers.go
- resources/mediastoredata-items.go
Works fine, but did trigger bug #157 in testing
> MediaStore Service, Hotfixed Signing Service for Data

- resources/autoscalingplans-scalingplans.go
> Fix Credential Scope

- resources/sns-endpoints.go
> Fix missing required parameters

- resources/sagemaker-notebookinstances.go
> fix SagemakerNotebookInstance not deleted

- glide.lock
- glide.yaml
> bump AWS SDK v1.13.60

- resources/s3-multipart-uploads.go
> Fixes https://github.com/rebuy-de/aws-nuke/issues/196
> add S3 multipart uploads

- README.md
- cmd/log.go
- cmd/nuke.go
- cmd/queue.go
- config/example.yaml
- pkg/config/filter.go
- resources/ec2-vpc.go
- resources/iam-role-policy-attachments.go
- resources/iam-user-access-keys.go
- resources/iam-user-policy-attachments.go
- resources/interface.go
- resources/route53-hosted-zones.go
- resources/route53-resource-records.go
- resources/s3-multipart-uploads.go
- resources/s3-objects.go
@rebuy-de/prp-aws-nuke Please take a look. What do you think?
/cc @tomvachon
>  add advanced filters via properties

- glide.lock
- glide.yaml
> bump AWS SDK v1.14.9

- cmd/scan.go
- pkg/awsutil/errors.go
- pkg/awsutil/session.go
> Fixes #154
@rebuy-de/prp-aws-nuke @tomvachon Please review.
> only warn on missing services for regions

- resources/appstream-directoryconfigs.go
- resources/appstream-fleets.go
- resources/appstream-fleetstates.go
- resources/appstream-imagebuilders.go
- resources/appstream-imagebuilderwaiters.go
- resources/appstream-images.go
- resources/appstream-stack-fleet-attachments.go
- resources/appstream-stacks.go
Note: per #122 I had to get a little creative around ImageBuilders.  I made a "Waiting" resource type which does nothing but ensure that whatever condition the ImageBuilder Remove() resource type needs can be satisified if its the last resource left in the Queue otherwise it will error out.
> Add AppStream 2.0 Service Coverage

- resources/acmpca-certificateauthorities.go
- resources/acmpca-certificateauthoritystates.go
Note: will remain in deleted state until purged by AWS within 30 days
> Add ACM Private CA

- resources/wafregional-ip-set-ips.go
- resources/wafregional-ip-sets.go
- resources/wafregional-rule-predicates.go
Some rules need to be cleaned up, before they can get deleted.
> delete WAF rules

- .gitignore
- resources/ec2-security-groups.go
* also gitignoring .idea files
> Allow filtering EC2SecurityGroup by property "GroupName"

- pkg/types/properties.go
- resources/wafregional-byte-match-set-tuples.go
- resources/wafregional-byte-match-sets.go
- resources/wafregional-ip-set-ips.go
- resources/wafregional-rate-based-rule-predicates.go
- resources/wafregional-rate-based-rules.go
> more WAF resources

- resources/sns-subscriptions.go
* Add paging support to SNSSubscription
* supposed to fix https://github.com/rebuy-de/aws-nuke/issues/228
> #228: add paging support to SNSSubscription

- cmd/nuke.go
The sentence "Would delete these resources." was missing a subject and felt weird to me.
@rebuy-de/prp-aws-nuke
> Minor rewording

- resources/ecs-services.go
- resources/ecs-taskdefinitions.go
Remove services and task definitions
Fixes #231
> ECS Services & Task Definitions

- resources/wafregional-regex-match-sets.go
- resources/wafregional-regex-match-tuples.go
- resources/wafregional-regex-pattern-sets.go
- resources/wafregional-regex-pattern-tuples.go
> Add WAF Regex-Pattern and -Match and their tuples and strings

- resources/cloudformation-stack.go
* enables paging support for Cloudformation Stacks
* more than just first 100 stacks will be found
> #240: Enable paging for CFN stacks

- resources/cloudformation-stack.go
So basically we try a normal deletion and **always** return an error. In the next run the resource will either be deleted and we're happy and move on or it will be in `DELETION_FAILED` state in which case we delete it while retaining all sub-resources.
@rebuy-de/prp-aws-nuke
> CFS deletion logic fix

- cmd/nuke.go
- pkg/awsutil/account.go
- pkg/awsutil/session.go
> fix nil dereference

- resources/ec2-network-interfaces.go
> nuke EC2 NetworkInterfaces

- resources/s3-buckets.go
As per https://github.com/rebuy-de/aws-nuke/issues/263, deletes all objects from a bucket before attempting to delete the bucket itself.
Closes #263
> Empty objects from S3 bucket before nuking

- resources/iam-roles.go
I've got a lot of roles... 🤦‍♂️ 
Based off the [ECR example](https://github.com/rebuy-de/aws-nuke/blob/master/resources/ecr-repository.go).
> Add pagination to IAMRoles resources.

- resources/autoscaling-lifecyclehooks.go
@rebuy-de/prp-aws-nuke please review
> Adds ASG lifecycle hooks

- resources/cloudformation-stack.go
this potentially fixes #280 
@rebuy-de/prp-aws-nuke
> Fix: Error checking should happen before anything else in CFS

- resources/lambda-event-source-mapping.go
> add lambda-event-source-mapping

- glide.lock
- glide.yaml
> Emerged from #306
/cc @sas-pemcne
> update AWS SDK 1.15.88

- resources/iam-role-policy-attachments.go
> Should fix #294
/cc @preeny95
> Handle errors in listing IAMRolePolicyAttachments more graceful

- resources/rds-clusters.go
- resources/rds-instances.go
This will disable deletion protection on RDS instances and clusters before removal. No extra calls are being made since the DeletionProtection boolean is being returned with the describe api call. Boolean is being stored in the struct under DeletionProtection and queried during removal of the resource. Instance or cluster is modified only if needed to avoid any extra api calls.
> Add deletion protection support for RDS

- resources/iam-login-profiles.go
Yet another fix for #294.
/cc @preeny95
> handle LoginProfile errors better

- resources/ec2-vpc-peering-connections.go
Add Support for deleting VPC Peering Connections as per #302
> VPC Peering Connections

- resources/sns-endpoints.go
- resources/sns-platformapplications.go
> filter SNS errors if operation is not supported in given region

- glide.lock
- glide.yaml
> update AWS SDK v1.17.3

- README.md
- cmd/nuke.go
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/config/filter.go
- pkg/config/test-fixtures/example.yaml
Readme should be enough to see what's up here.
> Add filter presets

- glide.lock
- glide.yaml
- pkg/awsutil/account.go
This might help to figure out why #338 fails. Also it is a good idea to have meaningful error message in general.
> improve error reporting

- resources/iam-role-policy.go
> Fixes #331
Additionally, it adds all properties to IAMRolePolicy resources.
> filter inline role policies for roles created by AWS

- README.md
Since this hurt a bit in my eye, let's keep this consistent.
> Keep apostrophes consistent

- resources/dynamodb-items.go
Fixes this error:
```
Listing DynamoDBTableItem failed:
ValidationException: Invalid ProjectionExpression: Attribute name is a reserved keyword; reserved keyword: Path
```
> fix DynamoDBItem listing

- resources/ec2-vpn-connections.go
Hello,
This quick and easy PR's sole purpose is to add tags to the VPN connection object.
Let me know if you have any remark.
Kind regards,
> Added tags list for vpn connections

- README.md
> Follow-up to https://github.com/rebuy-de/aws-nuke/issues/377
> clearify Docker section in the readme

- go.mod
- go.sum
> Upgrade aws-sdk-go to latest version

- resources/dynamodb-items.go
> Fixes #412
* Fix `ProjectionExpression`, so reserved keywords do not matter at all.
* Add properties.
> fix use of reserved keywords for DynamoDB

- resources/ec2-client-vpn-endpoint-attachments.go
- resources/ec2-client-vpn-endpoint.go
Added two new resources to remove from ec2 service
> Remove resources: EC2 Client VPN Endpoint and its attachment

- resources/route53-resource-records.go
`ListResourceRecordSets` only fetches the first 100 records on each call. With this pull requests it will fetch all the records.
> Fetch all Route53ResourceRecordSet

- pkg/awsutil/session.go
Should solve https://github.com/rebuy-de/aws-nuke/issues/435, but needs further testing.
> allow to run without speficying the profile

- resources/cloudwatchevents-rules.go
Resolves https://github.com/rebuy-de/aws-nuke/issues/448
> Add Force flag to CW events rule deletion

- resources/backup-plans.go
- resources/backup-selections.go
I've found that in practice AWS Backup service will sometimes paginate backup plan results despite the MaxResults setting.  This will also handle future situations with >100 plans in an account.
> handle pagination in backup-plan and backup-selection resources

- README.md
Updated wording on the warning to match the original intent of the message.
> update word choice on warning

- resources/eks-nodegroups.go
* added an implementation for aws eks nodegroups handling
> added eks nodegroup as resource

- resources/route53-resource-records.go
Delete all record sets of the type "NS" except for the default "NS" settings
> Delete all record sets of the type "NS" except for the default "NS" settings

- resources/route53-health-checks.go
There is a 100 item [maximum](https://github.com/aws/aws-sdk-go/blob/master/service/route53/api.go#L10895) to a route53 `ListHealthChecks` request.
> Handle pagination 101+ route53 healthchecks

- pkg/config/config.go
- resources/cloudformation-stack.go
PR for supporting disabling termination protection when deleting cloudformation stacks (#430)
> #430 - cloudformation support for disabling termination protection
