- cmd/nuke.go
The region was always the last one defined because that pointer always got overridden.  
Now the s3 nuking works normally again as well.
@rebuy-de/it-platform
> Fix wrong region for session

- resources/rds-instances.go
> See #40
Now it uses the `DBInstanceIdentifier` instead of `DBName`.
> don't use name as identifier with RDS instances

- resources/s3-buckets.go
- resources/util.go
> https://github.com/rebuy-de/aws-nuke/issues/43
I am not sure in which cases one of the two pointers might be null.
> fix another null pointer dereference in S3

- cmd/nuke.go
- cmd/scan.go
- cmd/scan_test.go
This improves the error handling. If a lister should fail *aws-nuke* will continue. It would look like this:
```
eu-west-1 - CloudFormationStack - 'acm-certificates' - filtered by config
=============
Listing with resources.ResourceLister failed:
runtime error: invalid memory address or nil pointer dereference
goroutine 27 [running]:
runtime/debug.Stack(0xe3fcc0, 0xe24f00, 0x17ffe60)
/home/sven/Data/Applications/golang/src/runtime/debug/stack.go:24 +0xa7
github.com/rebuy-de/aws-nuke/cmd.safeLister.func1(0xc4200fff18)
/home/sven/Data/Projects/src/github.com/rebuy-de/aws-nuke/cmd/scan.go:49 +0x75
panic(0xe24f00, 0x17ffe60)
/home/sven/Data/Applications/golang/src/runtime/panic.go:491 +0x283
github.com/rebuy-de/aws-nuke/resources.(*EC2Nuke).ListInstances(0xc42000e110, 0xc4201ce300, 0xc4ad80, …
```
> improve resilience

- resources/iam-role-policie-attachements.go
- resources/iam-roles.go
Add additional filters to prevent errors like that:
```
eu-west-1 - IamRolePolicyAttachement - 'AWSServiceRoleForEC2Spot -> AWSEC2SpotServiceRolePolicy' - UnmodifiableEntity: Cannot perform the operation on the protected role 'AWSServiceRoleForEC2Spot' - this role is only modifyable by AWS
status code: 400, request id: 5dce7817-d02c-11e7-a395-9be537ee44f3
eu-west-1 - IamRolePolicyAttachement - 'AWSServiceRoleForEC2SpotFleet -> AWSEC2SpotFleetServiceRolePolicy' - UnmodifiableEntity: Cannot perform the operation on the protected role 'AWSServiceRoleForEC2SpotFleet' - this role is only modifyable by AWS
status code: 400, request id: 5e5c38ec-d02c-11e7-821c-d1b97041f7ca
eu-west-1 - IamRolePolicyAttachement - 'AWSServiceRoleForOrganizations -> AWSOrganizationsServiceTrustPolicy' - …
```
> Add IAM role filters

- README.md
- cmd/config_test.go
- cmd/root.go
- config/example.yaml
- resources/ecr-repository.go
- resources/iam-group-policy-attachments.go
- resources/iam-groups.go
- resources/iam-instance-profile-roles.go
- resources/iam-instance-profiles.go
- resources/iam-list-user-group-attachments.go
- resources/iam-policies.go
- resources/iam-role-policy-attachments.go
- resources/iam-roles.go
- resources/iam-server-certificate.go
- resources/iam-user-access-keys.go
- resources/iam-user-policy-attachments.go
- resources/iam-users.go
- resources/listers.go
- resources/types.go
- Rename `Iam.*` to `IAM.*`: consistent with the other service names: `EC2`, `RDS`, `KMS` etc.
- Rename `IamUserAccessKeys` to `IAMUserAccessKey`: all other resources are singular.
- Rename `ECRrepository` to `ECRRepository`: All other resources are camel-cased.
The capitalisation of acronyms is still inconsistent when it comes to resource names:
- `EC2DhcpOption`, `EC2Vpc`, `EC2VpnGateway`, `EC2VpnGatewayAttachment`, `EC2VpnConnection`, `EC2VpcEndpoint`
- `EC2NetworkACL`
@rebuy-de/prp-aws-nuke: Should we follow golang's best practice and capitalise acronyms or follow the golang aws-sdk in camel-casing it?
> Consistent capitalisation

- resources/dynamodb-items.go
- resources/dynamodb-tables.go
- resources/listers.go
- resources/rds-dbparametergroups.go
- resources/types.go
- DynamoDB Tables are now removed
- DynamoDB Table Items are now removed
@rebuy-de/prp-aws-nuke please review
> CLOUD-1332 adds dynamodb items nuking

- cmd/config.go
- cmd/config_test.go
- cmd/nuke.go
- cmd/root.go
- cmd/test-fixtures/example.yaml
- pkg/awsutil/account.go
* move AWS account queries into `awsutil` package to slim down `cmd` package
* move account validation from `Nuke` to the actual config struct
* add tests for account validation
@rebuy-de/prp-aws-nuke Please review. 
This is a preparation for #66.
> Refactor AWS account validation

- resources/iam-user-policy.go
Please review @rebuy-de/prp-aws-nuke
> Add IAMUserPolicy resource

- cmd/config.go
- cmd/log.go
- cmd/root.go
- cmd/scan.go
- glide.lock
- glide.yaml
- pkg/awsutil/session.go
- pkg/awsutil/util.go
- pkg/util/indent.go
* replaces warning and error log function
* adds debug logs for AWS API requests
The debug logs will help resolving permission errors, like in #73.
> Add proper logger facility

- resources/s3-objects.go
- resources/util.go
> Closes #62 #64 #67
I tried to rebase or merge #67, but I horribly failed. Therefore I had to manually apply the patch. Changes from #67:
* uses the new resources API
* doesn't print and filter the version ID for latest object
* actually deletes the objects
> adds support for s3 object versions

- pkg/awsutil/util.go
- pkg/awsutil/util_test.go
I found another header which should be hidden in the debug log.
> hide more headers

- resources/ec2-images.go
- resources/ec2-snapshots.go
This fixes #78 and fixes #80 
```
us-east-1 - EC2Volume - 'vol-01901abaa8d296376' - triggered remove
us-east-1 - EC2Snapshot - 'snap-0a4b6c012e9d6a7ab' - InvalidSnapshot.InUse: The snapshot snap-0a4b6c012e9d6a7ab is currently in use by ami-a94db9d4
status code: 400, request id: 0a332abf-7537-4624-84c2-0568df4e39b4
us-east-1 - EC2Image - 'ami-a94db9d4' - triggered remove
us-east-1 - EC2Image - 'ami-ac4cb8d1' - triggered remove
Removal requested: 3 waiting, 1 failed, 43 skipped, 0 finished
us-east-1 - EC2Volume - 'vol-01901abaa8d296376' - waiting
us-east-1 - EC2Snapshot - 'snap-0a4b6c012e9d6a7ab' - removed
us-east-1 - EC2Image - 'ami-a94db9d4' - waiting
us-east-1 - EC2Image - 'ami-ac4cb8d1' - waiting
Removal requested: 3 waiting, 0 failed, 43 skipped, 1 finished
us-east-1 - EC2Volume - …
```
> Add EC2 Snapshot Deletion and AMI Deletion

- resources/elasticsearchservice-domain.go
- resources/sqs-queues.go
Note, deletion of ESS Domains is very long in wait times
> Add ElasticSearchService Domain and SQS Queue

- cmd/scan.go
Makes this:
```
RRO[0003] Listing with resources.ResourceLister failed. Please report this to https://github.com/rebuy-de/aws-nuke/issues/new.
!!! InvalidInputException: Domain-related APIs are only available in the us-east-1 Region. Please set your Region configuration to us-east-1 to create, view, or edit these resources.
!!! 	status code: 400, request id: 6599057b-26a0-11e8-9adb-839c15402d16 
```
to this:
```
ERRO[0006] Listing with LightsailDomain failed. Please report this to https://github.com/rebuy-de/aws-nuke/issues/new.
!!! InvalidInputException: Domain-related APIs are only available in the us-east-1 Region. Please set your Region configuration to us-east-1 to create, view, or edit these resources.
!!! 	status code: 400, request id: 171da9c9-26a1-11e8-ba98-d7a54aa6d996 
```
I …
> fix error reporting

- resources/lightsail-domains.go
Fixes this error:
```
ERRO[0004] Listing with LightsailDomain failed. Please report this to https://github.com/rebuy-de/aws-nuke/issues/new.
!!! InvalidInputException: Domain-related APIs are only available in the us-east-1 Region. Please set your Region configuration to us-east-1 to create, view, or edit these resources.
!!! 	status code: 400, request id: cf5a1f23-26a1-11e8-b93c-77bf2f94ebab
```
> Related to #124 
/cc @tomvachon
> fix ligthsail region

- cmd/scan.go
- pkg/awsutil/account.go
- pkg/awsutil/errors.go
- pkg/awsutil/session.go
> Fixes #123
This is a breaking change and will cause a new major version.
/cc @tomvachon
>  introduce global region

- resources/s3-buckets.go
- resources/util.go
> Emerged from #139
Fixed bucket deletion, if the bucket is in `us-east-1`.
*(Now we now [in which cases the pointer might be `nil`](https://github.com/rebuy-de/aws-nuke/pull/44).)*
/cc @tomvachon
> fix S3 Bucket location

- resources/ses-configurationsets.go
- resources/ses-identities.go
- resources/ses-receiptfilters.go
- resources/ses-receiptrulesets.go
- resources/ses-templates.go
We cannot delete the Active Rule Set and there is no SDK function to invoke the "SetActiveReceiptRuleSet" API, so I am filtering it via a secondary describe call and a name matching
> Add SES Support

- resources/wafregional-rules.go
- resources/wafregional-webacl-rule-attachments.go
- resources/wafregional-webacls.go
Note: WAFRegional re-uses WAF types for Inputs
This is not full coverage of the product but does cover all "cost"-based assets
> Add WAF Regional Support for Rules and WebACLs

- README.md
- pkg/config/config_test.go
- pkg/config/test-fixtures/example.yaml
it's always plural, see also #171
> fix more typos - fixes #170

- resources/opsworks-userprofiles.go
This prevents the attached error when attempting deletion of this resource via filtering beforehand:
```
[slindauer] mordor-east-1 - OpsWorksUserProfile - 'arn:aws:iam::XXXXXXXXXXXX:user/foobar' - ValidationException: Cannot delete self
[slindauer]     status code: 400, request id: XXXXXXXXX-XXXX-XXXX-XXXXXXXX
```
Please review @rebuy-de/prp-aws-nuke
> Filter calling OpsWorksUserProfile

- resources/ec2-placement-groups.go
- resources/ec2-security-groups.go
- resources/s3-buckets.go
* add EC2 placement groups
* security groups: revoke all IP permissions before destroying
It's possible for security groups to have circular dependencies on each
other, preventing the actual removal from ever working. If we remove the
rules first, it's possible for a future retry to succeed.
* don't fail entire S3 bucket list on one bucket
It's possible for a single S3 bucket to be in an undesirable state (i.e.
unattached to a region) and this will cause all buckets to be filtered.
> add placement groups, fix security group circular deps, s3 bucket filtering enhancement

- README.md
* targets "https://github.com/rebuy-de/aws-nuke/blob/master" which results in 404 for me
* changed it to target "https://github.com/rebuy-de/aws-nuke/releases"
> Fix Release Batch on top of README

- pkg/awsutil/session.go
> Fixes #208 
[`LookupAddr`](https://golang.org/pkg/net/#LookupAddr) does a revers IP lookup and [`LookupHost`](https://golang.org/pkg/net/#LookupHost) does what we actually want. No idea how I did this wrong and how it worked in my tests.
@rebuy-de/prp-aws-nuke @tomvachon Please review.
> fix hostname check

- pkg/types/properties.go
- resources/ec2-security-groups.go
- resources/ec2-vpc.go
- resources/iam-role-policy-attachments.go
- resources/iam-user-access-keys.go
- resources/iam-user-policy-attachments.go
- resources/interface.go
- resources/route53-hosted-zones.go
- resources/route53-resource-records.go
- resources/s3-multipart-uploads.go
- resources/s3-objects.go
- resources/wafregional-ip-set-ips.go
- resources/wafregional-ip-sets.go
- resources/wafregional-rule-predicates.go
I think it makes more sense to move the `Property` type into the `type` package.
> move properties

- cmd/log.go
- cmd/nuke.go
- cmd/queue.go
- pkg/types/properties.go
- pkg/types/properties_test.go
- resources/dynamodb-items.go
- resources/interface.go
Make resource IDs optional (ie IDs from `String()` function). New resources should use the property feature instead.
Making legacy to avoid awkward resource IDs like this in `wafregional-ip-set-ips.go`:
```golang
return fmt.Sprintf("%s -> %s:%s", *r.ipSetid, *r.descriptor.Type, *r.descriptor.Value)
```
Describing [`waf.FieldToMatch`](https://godoc.org/github.com/aws/aws-sdk-go/service/waf#FieldToMatch) in a single string would be even more complex.
> make resource ID optional

- resources/elasticbeanstalk-environments.go
It's easier to filter ElasticBeanstalkEnvironments by a property that's human-readable.
> Allow ElasticBeanstalkEnvironments to be filtered by Name

- README.md
- cmd/nuke.go
- cmd/util.go
- cmd/util_test.go
- pkg/config/filter.go
Hi!
`invert: true` can be added to any filter statement and would invert such filter result. 
Can be useful to not only protect resources from being nuked, but to also explicitly define resources to be removed by inverting a filter result (else used for resource protection).
Cheers, Christian
> Allow to invert Filter Results

- pkg/types/properties.go
Apparently a `nil` check does not work for `interface{}`.
> fix null dereference

- .gitignore
- config/example.yaml
- pkg/types/properties.go
- resources/cloudformation-stack.go
@svenwltr  - this is what I had in mind. Not sure we need an extra Map for tags...
let me know what you think. @leflamm interesting for you too :)
> Initial version of tag-based filterring

- resources/cloudformation-stack.go
This would be my suggestion on how to deal with CloudFormationStacks that get stuck in _**Deletion failed**_ state.
By retaining all resources that belong to the CloudFormationStacks we delete **just** the CloudFormationStack resource and **don't** cause cascading deletions. 
IMHO this should be the desired behavior. As with other resources, we just try to delete the resource itsself **EXcluding** the onces that depend on it.
The resources that were created from the CloudFormationStack and are left over after the CloudFormationStack is gone, should be deleted by their own resource implementation.
What do you think? 
ref: https://github.com/rebuy-de/aws-nuke/issues/238
ping @rebuy-de/prp-aws-nuke
> Retain all CloudFormation resources in Deletion of CloudFormationStack

- resources/cloudformation-stack.go
Turns out the conditions under which this solution was tested were flawed. Resources can only be retained when the CFS is already in `DELETE_FAILED` state.
Therefore we have to find a different solution to fix CFS. :crying_cat_face: 
Reverts rebuy-de/aws-nuke#242
> Revert "Retain all CloudFormation resources in Deletion of CloudFormationStack"

- golang.mk
Adding the `-s -w` ldflags on build [strips debugging symbols](https://blog.filippo.io/shrink-your-go-binaries-with-this-one-weird-trick/
) and reduces the resulting binary size by about a third before compression
```
❯ ls -lh aws-nuke*
-rwxr-xr-x  1 mark  staff    99M Aug 29 09:09 aws-nuke-v2.4.0.5.gfac485d-darwin-amd64
-rwxr-xr-x  1 mark  staff    67M Aug 29 09:11 aws-nuke-v2.4.0.5.gfac485d.dirty-darwin-amd64
```
```
❯ ./aws-nuke-v2.4.0.5.gfac485d.dirty-darwin-amd64 version
version:     v2.4.0.5.gfac485d.dirty
build date:  Wed Aug 29 09:10:56 MDT 2018
scm hash:    fac485df12c04ccbfccccbd5d7ce7623d005a1c5
environment: mark@Marks-MacBook-Pro.local
```
> Strip debug info using ldflags on build

- cmd/nuke.go
- cmd/params.go
- cmd/root.go
- main.go
We want to get to a point where we can run `aws-nuke` through our CI/CD platform and have noticed that it can get stuck in a waiting state for a considerable length of time in some scenarios. 
This pull request aims to resolve that by adding a flag that, if set, will cause the program to bail out if it is waiting for `n` number of iterations and no new work has been discovered in that time.
> Add --max-wait-retries flag to bail out early if the script is stuck waiting

- resources/iam-group-policies.go
Adds a new resource for deleting IAM group inline policies. Without this resource, any IAM group with inline policies is not nuke-able:
```
global - IAMGroup - build.AdminRole - DeleteConflict: Cannot delete entity, must delete policies first.
--
  | status code: 409, request id: ecb65335-c23f-11e8-a1c3-132b0b63d06b
```
> Add IAMGroupPolicy resource

- resources/cloudformation-stack.go
As described in https://github.com/rebuy-de/aws-nuke/issues/270 aws-nuke retains resources that are already in `DELETE_COMPLETE` state.
In order to not run into an error message here, we exclude them from the retain array.
> Fix deletion of resources in DELETE_COMPLETE state

- pkg/types/properties.go
- pkg/types/properties_test.go
- resources/ec2-instances.go
- resources/ec2-internet-gateway-attachments.go
- resources/ec2-internet-gateways.go
- resources/ec2-nat-gateways.go
- resources/ec2-route-tables.go
- resources/ec2-subnets.go
- resources/ec2-volume.go
- resources/ec2-vpc.go
- resources/ec2-vpcEndpoint.go
- resources/ec2-vpn-gateway-attachments.go
- resources/elb-elb.go
- resources/elbv2-alb.go
- resources/elbv2-targetgroup.go
- resources/iam-instance-profile-roles.go
- resources/iam-instance-profiles.go
- resources/iam-policies.go
- resources/iam-role-policy-attachments.go
- resources/iam-role-policy.go
I've mostly copied what was done over in #237 and extended it to resource types that I need to filter based on tag values.
There were two resource types that I've made a potentially controversial decision about: `EC2InternetGatewayAttachment`, `EC2VPNGatewayAttachment`, and `EC2VPCEndpoint`. For `EC2InternetGatewayAttachment` and `EC2VPNGatewayAttachment` I have chosen to inherit the tags from the Internet/VPN Gateway as a gateway would be more likely to have more specific tags than the VPC it lives in. If we should include both sets of tags I'm also fine with that, I just can't think of a good way to display both with the current key/value pairing.
For EC2VPCEndpoint I've just inherited the tags from the containing VPC.
> Add tags to more resources

- README.md
There can never be enough warnings about this. Please take a look at the wording.
Also I rephrased the description, because the term *nuke* is not really descriptive.
> add more warnings to the readme

- resources/iam-open-id-connect-provider.go
- resources/iam-saml-provider.go
Added the capability to nuke specific SAML and OpenIdConnect Identity Providers.
This has been tested using ADFS within our test infrastructure.
> Allow nuking of SAML and OpenIdConnect Identity Provider

- resources/elb-elb.go
> Fixes #295 
It looks like the error in #295 only appears, if there is not a single ELB.
> fix listing ELBs

- golang.mk
- resources/dynamodb-items.go
Our DynamoDB had a primary key called `hash`. This created an error because it is a reserved keyword, so I created a workaround for this specific case.
> Fix for using DynamoDB with reserved keywords

- resources/iam-service-specific-credentials.go
I was hitting an error with the nuker involving IAM user dependencies:
```
global - IAMUser - test - DeleteConflict: Cannot delete entity, must remove referenced objects first.
status code: 409
```
This is due to service specific credentials being attached to the user that need to be deleted first. I have added a new resource called IAMServiceSpecificCredential which gathers all of these keys from IAM users. 
I included the credential's service (gathered from the Describe api call) to include in the nuker output. I think codecommit is the only service right now but I thought being verbose in the output would be good in case they add more services in the future. Output will be the following in `iam-user -> [cred-service] service-credential-name` format.
```
global - …
```
> Added IAMServiceSpecificCredentials resource

- resources/ec2-vpc-endpoint-service-configurations.go
I have added a new resource EC2VPCEndpointServiceConfiguration that will support private links within the VPC. These are different from the VPC Endpoints which there is already a resource. I tried to mimic the EC2VPCEndpoint resource as much as possible but just wanted to note that filtering by `vpc-id` is not supported in the [DescribeVpcEndpointServiceConfigurations API call](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeVpcEndpointServiceConfigurations.html). This does mean that VPC filters on the nuke configuration will not exclude this resource, let me know if that's an issue and I can try and figure out a work around. 
The resource name is quite long but I wanted to stay consistent with the project and the APIs. Let me know if you have any alternative …
> Added resource EC2VPCEndpointServiceConfiguration

- resources/fsx-backups.go
- resources/fsx-filesystems.go
I have added two new resources to support FSx: FSxFileSystem and FSxBackup. Tags and the Type are being set in the properties. 
Output will be similar to the following:
```
us-east-2 - FSxBackup - backup-08fa7bdc34499d283 - [Type: "AUTOMATIC"] - would remove
us-east-2 - FSxBackup - backup-0425e8b5689f67c6d - [tag:Name: "pemcne-test-backup", Type: "USER_INITIATED"] - would remove
us-east-2 - FSxFileSystem - fs-0cdc6d27c6cebb7d8 - [tag:Name: "pemcne-test", Type: "LUSTRE"] - would remove
us-east-2 - FSxFileSystem - fs-00366030c6a1d9207 - [tag:Name: "pemcne-test", Type: "WINDOWS"] - would remove
Scan complete: 4 total, 4 nukeable, 0 filtered.
```
> Add resources for FSx filesystems and backups

- resources/elasticache-replicationgroups.go
Adds an `ElasticacheReplicationGroup` resource. There is some overlap between this resource and the `ElasticacheCacheCluster` resource in that a replication group consists of multiple cache clusters. The problem though is that cache clusters that are part of a replication group aren't being deleted on their own, due to errors similar to the following:
```
InvalidCacheClusterState: Cache cluster transactions-001 is serving as primary for replication group transactions and cannot be deleted. To delete the entire replication group, use DeleteReplicationGroup.
--
  | status code: 400, request id: eb3f1c2e-c23f-11e8-a902-65beaf280fb2
```
> Add ElasticacheReplicationGroup resource

- resources/ec2-subnets.go
Similar to issue https://github.com/rebuy-de/aws-nuke/issues/188 (implemented in https://github.com/rebuy-de/aws-nuke/pull/198), which allowed for easy filtering of the default VPC, this does the same for default subnets.
You can use it like so:
```yaml
accounts:
"1234567890":
filters:
EC2Subnet:
- property: DefaultForAz
value: "true"
```
> Add 'DefaultForAz' property for subnets

- README.md
Really tiny commit so we only link to HTTPS resources.
@rebuy-de/prp-aws-nuke
> Switch AWS docs link to https

- README.md
- cmd/nuke.go
- cmd/queue.go
- cmd/scan.go
This PR has two changes, that have the goal to reduce obscurities in new issues:
* It does not show the link to the "Create Issue" page anymore, since I assume this encourages people to create new issues, although they are not affected by these errors. The reason for this is, that AWS inevitably produce errors on some region-service configurations, which are hard to fix.
* The second change hides the error message of AWS in intermediate nuke runs and just prints `failed` instead. If the nuke aborts due to many errors, it will print all remaining errors in the end. The reason for this change is, that new issues often just report just a single line like [1] and we cannot be sure if this is actually a final error or they just reported the error, because they did not fully understand how …
> show less errros

- cmd/nuke.go
- cmd/params.go
- cmd/root.go
- main.go
this is most useful if run as part of a lambda, where sleeps == $$.
> add --force-sleep param instead of statically setting the wait to 15 seconds

- resources/ec2-tgw-attachments.go
- resources/ec2-tgw.go
Support for transit gateways and vpc attachments.
VPN attachments to transit gateways are deleted as part of VPN Connections
> add support for Transit gateways and its vpc attachments

- config/example.yaml
- resources/backup-plans.go
- resources/backup-recovery-points.go
- resources/backup-selections.go
- resources/backup-vaults.go
- resources/ec2-snapshots.go
* Added these AWS Backup resources:
* Backup plans
* Backup vaults
* Backup selections
* Recovery points
* Added ability to filter EC2 snapshots by tags - AWS snapshots are reserved and cannot be nuked through EC2 so a user can exclude AWS reserved-snapshots by filtering on something like this:
```yaml
presets:
non_aws_backup_snapshots:
filters:
EC2Snapshot:
- property: "tag:aws:backup:source-resource"
type: regex
value: ".+"
```
```yaml
regions:
- global
- us-east-1
account-blacklist:
- "999999999999" # placebo production account
accounts:
238403284032840:
presets:
- "non_aws_backup_snapshots"
resource-types:
targets:
- EC2Snapshot
- AWSBackupPlan
- AWSBackupVault
- AWSBackupSelection
- AWSBackupRecoveryPoint
presets:
non_aws_backup_snapshots:
filters:
EC2Snapshot:
- property: …
```
> Add AWS Backup resources 

- config/example.yaml
- resources/ec2-images.go
Found that I was unable to filter certain AMIs via tags. This allows us to filter certain AMIs via tags
```
us-west-2 - EC2Image - ami-1234567df81e826c58 - [tag:release: "production", tag:database: "cassandra"] - filtered by config
us-west-2 - EC2Image - ami-1234553054dc19d83 - [tag:operating_system: "ubuntu"] - would remove
```
```
resource-types:
targets:
- EC2Image
accounts:
123456789:
filters:
EC2Image:
- property: "tag:release"
value: "production"
```
> Enable Tag filter on EC2 Images

- cmd/nuke.go
This is in response to #355. aws-nuke now returns error when threshold is reached
> return error when max wait threshold is reached

- config/example.yaml
- resources/msk-cluster.go
An attempt to register MSK Service requested in issue #354 
```
rabbbithole$ docker run -a stdin -a stdout -ti rebuy-de/aws_nuke -c config/example.yaml --secret-access-key=$AWS_SECRET_ACCESS_KEY --access-key-id=$AWS_ACCESS_KEY_ID
aws-nuke version v2.10.0.4.g6b3bdb7.dirty - Sat Apr 27 07:01:51 UTC 2019 - 6b3bdb7c2bc4dfb65b08ec404983539b059fe243
Do you really want to nuke the account with the ID 12344123445 and the alias 'test-account'?
Do you want to continue? Enter account alias to continue.
> test-account
us-east-2 - MSKCluster - arn:aws:kafka:us-east-2:12344123445:cluster/test-cluster/4a914bb3-cadd-4e2c-b9d8-ad8166d381ff-3 - [Arn: "arn:aws:kafka:us-east-2:12344123445:cluster/test-cluster/4a914bb3-cadd-4e2c-b9d8-ad8166d381ff-3", Name: "test-cluster"] - would remove
Scan complete: 1 …
```
> Register MSK service

- resources/ec2-dhcp-options.go
Many thanks for a very useful project.
I ported https://github.com/rebuy-de/aws-nuke/commit/4dfad10643e291fa3353b82fe23ffe614f0b91f0 for EC2 DHCP Options.
I am actually using this patch.
> Enable tags for EC2 DHCP Options

- resources/dynamodb-tables.go
- resources/lambda-functions.go
- resources/rds-clusters.go
- resources/rds-dbclusterparametergroups.go
- resources/rds-dbparametergroups.go
- resources/rds-instances.go
- resources/rds-subnets.go
- resources/s3-buckets.go
- resources/s3-objects.go
Added tag properties to S3 bucket, RDS resources (snapshots already had tags), DynamoDB Tables, and lambda functions.
I originally tried adding tags for S3 Objects, but I realized the API Call across several buckets with thousands of objects could get VERY costly. Because of this, I took that out and decided not to add any additional properties to S3 Objects.
> Add tag filter for S3 Bucket, RDS Resources, DynamoDB Tables, Lambda Functions

- resources/s3-buckets.go
Untagged buckets get returned an error from GetBucketTagging API call. So, buckets without tags currently do not get displayed. This fix now will only skip buckets on actual api call errors.
Sorry I didn't catch this when I pushed these changes earlier :/
> Fix: catch s3 bucket tag error properly

- cmd/log.go
This ensures that multiple runs of aws-nuke produce stable output so
that they can be compared with each other.
This is likely terrible golang style/design.  Happy to take advice on how to make it more idiomatic.
> Format resource properties in sorted order

- resources/ec2-volume.go
Added state as an additional filter option for ec2 volumes. I think this might be useful in the event that you want to only 'nuke' volumes currently going unused. 
Tested with volumes in various states with config:
```
EC2Volume:
- property: 'State'
value: 'in-use'
```
> feat: Add State as filter option for ec2 volumes

- resources/iot-certificates.go
- resources/iot-policies.go
- resources/iot-things.go
This PR addresses the points detailed in #374. 
Changes:
- Now detaches attached principals to IoT things prior to deletion
- Now detaches attached targets to IoT policies prior to deletion
- Now deprecates non-default versions of IoT policies prior to deletion
- Now deactivates IoT certificates prior to deletion
> Adds additional AWS IoT considerations for deletion

- resources/iam-virtual-mfa-devices.go
Virtual MFA devices were not being cleaned and caused an IAM user delete to fail with the following message. I added Virtual MFA devices to resolve the issue
```
global - IAMUser - myuser - failed
ERRO[0931] DeleteConflict: Cannot delete entity, must delete MFA device first.
status code: 409, request id: bb7949c0-d3ff-11e9-a56a-e1f2488279d7
Error: failed
```
> Adding virtual-mfa-devices resource

- resources/iam-group-policy-attachments.go
We wanted to filter by the group on the group policy attachments but it was difficult without exposing the properties. I have added the group policy attachment properties to be exposed the same way IAMRolePolicyAttachment is done.
> Adding filters to group policy attachments

- resources/worklink-fleets.go
Added support for nuking WorkLink Fleets, resolving my own issue #368.
Sample output:
```
eu-west-1 - WorkLinkFleet - test - [CompanyCode: "a9426d1a"] - would remove
eu-west-1 - WorkLinkFleet - test2 - [CompanyCode: "d9dc1669", DisplayName: "test2 Display Name"] - would remove
Scan complete: 2 total, 2 nukeable, 0 filtered.
```
> Add WorkLink support

- resources/ec2-instances.go
Currently EC2 instance listing is not being paginated, this adds pagination.
> paginate ec2 instances

- cmd/nuke.go
- cmd/params.go
- cmd/root.go
- main.go
Without this change, output showing what is (or will be) removed can
easily be lost on the output showing filtered resources.  It's useful
to be able to just see what is (or will be) affected in order to focus
on that.
> Add --quiet flag to remove filtered resources from output

- cmd/nuke.go
This fix corrects an issue where the nuker does not correctly handle resources from multiple regions in a single run.
Currently, the nuker logic, specifically in the `HandleWait` function, is as follows:
1. Try and get the item type out of the cache
2. If the item type does not exist, list the resources and add to the cache
3. Loop through cached resources and try to find a match for our item id
4. If our item isn't in the cache, it has been deleted
The flaw in this design is that the `item.List()`, called in step 2 above, only lists items for a single region (assuming the resource is region specific). Because of this, the cache will not be accurate for any region outside of the region that the item was in.
Consider the following scenario, nuker runs on two regions: us-east-1 and …
> Add another layer to the cache to keep regions separated

- CONTRIBUTING.md
Remove some git instruction from `CONTRIBUTING.md`, because we are going to squash PR to make everybody's life easier.
> simplify contibuting guidelines

- resources/athena-named-queries.go
- resources/athena-work-groups.go
Add support for deleting Athena WorkGroups and NamedQueries. Resolves #464 
Note that WorkGroups and NamedQueries are the only two modifiable Athena resources. See https://docs.aws.amazon.com/cli/latest/reference/athena/index.html
Adding some complexity here: there's a default `"primary"` WorkGroup in Athena that can't be deleted. So in order to meet our business requirements of getting accounts back in a "clean" state, the aws-nuke `WorkGroup` resource will modify the `"primary"` WorkGroup to get it back in its original state.
I tested this out by creating some Athena resources via the web console, then running aws-nuke.
Selected aws-nuke output:
```
us-east-1 - AthenaNamedQuery - 522280c2-d6ad-4fd5-a8f5-eb041dc55e44 - [Id: "522280c2-d6ad-4fd5-a8f5-eb041dc55e44"] - would remove
us-east-1 …
```
> Add support for Athena WorkGroups and NamedQueries

- resources/route53-health-checks.go
This adds support for nuking Route53 health checks.
Sample output:
```bash
global - Route53HealthCheck - 483e892d-2508-4d94-bd6f-c93899a227d5 - [ID: "483e892d-2508-4d94-bd6f-c93899a227d5"] - removed
global - Route53HealthCheck - 5a3da0e5-b75d-4361-9e14-4dc43791520b - [ID: "5a3da0e5-b75d-4361-9e14-4dc43791520b"] - removed
global - Route53HealthCheck - 922e3b9b-0fcf-4563-926c-20c2584687db - [ID: "922e3b9b-0fcf-4563-926c-20c2584687db"] - removed
global - Route53HealthCheck - 9958f9d6-5b82-42c5-a6fb-e76569ac3ff7 - [ID: "9958f9d6-5b82-42c5-a6fb-e76569ac3ff7"] - removed
global - Route53HealthCheck - a1ef5f16-d575-4ac3-b3a5-c08a3702ff7f - [ID: "a1ef5f16-d575-4ac3-b3a5-c08a3702ff7f"] - removed
global - Route53HealthCheck - bbf4907a-00f9-4e45-b9d0-a3103e03996a - [ID: …
```
> add route53 health check resource

- resources/ec2-tgw.go
Adds OwnerId property to EC2TGW - Required when the TGWs are shared as an Organization level and can not be removed from the sub-account.
> feat: Add OwnerId Prop to EC2TGW

- resources/securityhub-hub.go
See https://github.com/rebuy-de/aws-nuke/issues/452
Add the ability to detect regions with Security Hub enabled and disable it if a
"hub" resource is returned.
> Disable Security Hub

- config/example.yaml
Replace the wildcard to ** to allow recurside sublevel directories in
the nuke process.
> Replace Regex in S3Object sample to recursive nuke

- resources/ec2-eip.go
- resources/ec2-security-groups.go
- resources/iam-roles.go
add tag support to ec2 security groups
add tag support to iam roles
add tag support to elastic ip addresses
> Additional tag support
